# Datapath configuration

base_data_dir: "datasets/"


single_pose:
  pinch:
    "0": "rep0_pinch.bag"
    "1": "rep1_pinch.bag"
    "2": "rep2_pinch.bag"
  ulnar:
    "0": "rep0_ulnar.bag"
    "1": "rep1_ulnar.bag"
    "2": "rep2_ulnar.bag"
  power:
    "0": "rep0_power.bag"
    "1": "rep1_power.bag"
    "2": "rep2_power.bag"

pinch_x3: ["pinch", "pinch", "pinch"]
ulnar_x3: ["ulnar", "ulnar", "ulnar"]
power_x3: ["power", "power", "power"]
pinch_ulnar_power_x3: ["pinch", "pinch", "pinch", "ulnar", "ulnar", "ulnar", "power", "power", "power"]

pinch_ulnar_power: ["pinch", "ulnar", "power"]
combination_2: ["pinch", "ulnar", "power", "pinch"]


emg_topic: "emg_rms"

