# ==================================================
# Configuration file for the muscle synergy analysis project.
# ==================================================

base_data_dir: "C:/Users/ricca/Desktop/th_unibo/muscle_synergy_analysis/datasets/"

single_pose:
  pinch:
    "0": "rep0_pinch.bag"
    "1": "rep1_pinch.bag"
    "2": "rep2_pinch.bag"
  ulnar:
    "0": "rep0_ulnar.bag"
    "1": "rep1_ulnar.bag"
    "2": "rep2_ulnar.bag"
  power:
    "0": "rep0_power.bag"
    "1": "rep1_power.bag"
    "2": "rep2_power.bag"

pinch_ulnar_power: ["pinch", "ulnar", "power"]

emg_topic: "emg_rms"

