# ==================================================
# ROS Bag File Paths
# ==================================================

base_data_dir: "C:/Users/ricca/Desktop/th_unibo/muscle_synergy_analysis/datasets/"

single_pose:
  pinch:
    "0": "rep0_pinch.bag"
    "1": "rep1_pinch.bag"
    "2": "rep2_pinch.bag"
  ulnar:
    "0": "rep0_ulnar.bag"
    "1": "rep1_ulnar.bag"
    "2": "rep2_ulnar.bag"
  power:
    "0": "rep0_power.bag"
    "1": "rep1_power.bag"
    "2": "rep2_power.bag"

pinch_ulnar_power: ["pinch", "ulnar", "power"]

# ==================================================
# Analysis Parameters
# ==================================================

emg_topic: "emg_rms"

nmf_params:
  max_synergies: 8
  min_synergies: 1
  alpha_values: [0.001, 0.005, 0.01, 0.05, 0.1]
  l1_ratio: 0.7
  max_iter: 500
  random_state: 42
  init: "nndsvd"

cv_params:
  n_folds: 3
  var_weight: 0.6
  sparsity_weight: 0.3
  cond_weight: 0.1

vis_params:
  figsize: [10, 8]
  color_palette: "viridis"
  line_width: 1.5
